services:
  control-plane:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/control-plane"]
    environment:
      CP_HTTP_ADDR: ":8080"
      CP_XDS_ADDR: ":18000"
      CP_RECONCILE_INTERVAL: "1s"
      CP_STALE_AFTER: "15s"
    ports:
      - "8080:8080"
      - "18000:18000"
    networks: [mesh]

  backend-a:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["-addr=:9000", "-name=backend-a"]
    networks: [mesh]

  envoy-dynamic:
    image: envoyproxy/envoy:v1.31-latest
    volumes:
      - ./deployments/envoy/envoy-dynamic.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "20000:20000"
      - "9901:9901"
    depends_on: [control-plane]
    networks: [mesh]

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [mesh]

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./deployments/docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./deployments/docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    networks: [mesh]

networks:
  mesh:
    driver: bridge
