global:
  scrape_interval: 5s

scrape_configs:
  - job_name: control-plane
    static_configs:
      - targets: ["control-plane:8080"]

  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ["envoy-dynamic:9901"]
